config/routes.rb
Rails.application.routes.draw do

  # devise_scope :user do
  #   get "/users/sing_out" => "devise/sessions#destroy"
  # end

  # devise_for :users

  resources :items do
    get :upvote,     on: :member
    get :expensive,  on: :collection
    get :crop_image,  on: :member
    put :crop_image,  on: :member
  end
  get "admin/users_count" => "admin#users_count"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  # attr_accessible :title, :body

has_many :comments, as: :commentable

end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :positions
  belongs_to :user
  has_and_belongs_to_many :items
  has_many :items, through: :positions

end

app/models/comment.rb
class Comment < ApplicationRecord
  # attr_accessible :body, :user_id, commentable_id, :commentable_type

  belongs_to :user
  belongs_to :commentable, polymorphic: true

end

app/models/item.rb
class Item < ApplicationRecord
  # attr_accessible :price, :name, :weight, :real, :description
  #
  validates :price, numericality: { greater_than: 0, allow_nil: true }
  validates :name, presence: true

  has_many :positions
  has_many :carts, through: :positions
  has_many :comments, as: :commentable

  # after_initialize { } # Item.new, Item.first
  # after_save { } # Item.save, Item.create, item.update_attributes()
  # after_create { ItemMailer.new_item_created(self).deliver } - example
  # after_update { }
  # after_destroy { }
end

app/models/order.rb
class Order < ApplicationRecord
  # attr_accessible :user, :user_id
  belongs_to :user
end

app/models/position.rb
class Position < ApplicationRecord
  # attr_accessible :item_id, :cart_id, :quantity

  belongs_to :item
  belongs_to :cart

end

app/models/user.rb
class User < ApplicationRecord
  # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # attr_accessible :login, :email, :password, :password_confirmation, :remember_me

  has_one :cart
  has_many :orders
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def render_403
    render file: "public/403.html", status: 403
  end

  def render_404
    render file: "public/404.html", status: 404
  end

  def check_if_admin
    render_403 unless params[:admin] # current_user.admin == true
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]

  def index
    @items = Item.all
  end

  def expensive
    @items = Item.where("price > 1000")
    render "index"
  end

  # /items/1 GET
  def show
    unless @item
      render plain: "Page not found", status: 404
    end
  end

  #/items/new GET
  def new
    @item = Item.new
  end

  #/items/1/edit GET
  def edit
  end

  # /items POST
  def create
    @item = Item.create(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render 'new'
    end
    # render plain: "#{@item.id}: #{@item.name} (#{!@tem.new_record?})"
    # render plain: params.inspect
  end

  # /items/1 PUT/
  def update
    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  # /items/1 DELETE
  def destroy
    @item.destroy
    # redirect_to items_path
    redirect_to action: "index"
  end

  def upvote
    @item.increment!(:votes_count)
    redirect_to action: :index
  end

  private

  def item_params
    params.require(:item).permit! # или (:price, :name, :description, :weight, :real, :image)
  end

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit item </h1>
<%= form_for @item do |f| %>

  <p>Price: <br/><%= f.text_field :price %></p>
  <p>Name: <br/><%= f.text_field :name %></p>
  <p>Description: <br/><%= f.text_field :description %></p>
  <p>Weight: <br/><%= f.text_field :weight %></p>

  <p><%= f.submit "Edit tovar" %></p>
<% end %>

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
  <b>No items in store</b>
<% else %>
  <table>
    <tr>
      <th>item id   </th>
      <th>  Name_items   </th>
      <th>  Price_items   </th>
      <th></th>
      <th></th>
    </tr>
    <% @items.each do |i| %>
      <tr>
        <td><%= i.id %></td>
        <td><%= link_to i.name, item_path(i) %></td>
        <td><%= i.price %> dol. </td>
        <td><%= link_to "Delete", item_path(i), method: :delete, data: { confirm: "Are you sure?" } %></td>
        <td>Rating: <%= i.votes_count %><%= link_to "+", upvote_item_path(i) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/items/new.html.erb
<h1>Create new item </h1>
<%= form_for @item do |f| %>

  <p>Price: <br/><%= f.text_field :price %></p>
  <p>Name: <br/><%= f.text_field :name %></p>
  <p>Description: <br/><%= f.text_field :description %></p>
  <p>Weight: <br/><%= f.text_field :weight %></p>

  <p><%= f.submit "Create tovar" %></p>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<ul>
  <li><%= @item.price %>dol.</li>
  <li>Desc: <%= @item.description %></li>
  <li>Weight: <%= @item.weight %>kg.</li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>